dbt_youtube:
  outputs:
    dev:
      account: sdxclvm-iq47862
      database: TUKI_DB
      password: '!Tutempgmail01'
      role: TUKI_ROLE
      schema: TUKI_DEV_SCHEMA
      threads: 1
      type: snowflake
      user: tutempgmail01
      warehouse: TUKI_WH
    prod:
      account: sdxclvm-iq47862
      database: TUKI_DB
      password: '!Tutempgmail01'
      role: TUKI_ROLE
      schema: TUKI_PROD_SCHEMA
      threads: 1
      type: snowflake
      user: tutempgmail01
      warehouse: TUKI_WH
  target: dev