-- Chuyển sang role ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Tạo data warehaouse
CREATE WAREHOUSE TUKI_WH WITH WAREHOUSE_SIZE = 'X-SMALL';

-- Tạo database
CREATE DATABASE TUKI_DB;

-- Tạo role cho DBT
CREATE ROLE TUKI_ROLE;

-- Kiểm tra quyền trên warehouse
SHOW GRANTS ON WAREHOUSE TUKI_WH

-- Gán quyền sử dụng warehouse
GRANT USAGE ON WAREHOUSE TUKI_WH TO ROLE TUKI_ROLE;

-- Gán role cho user
GRANT ROLE TUKI_ROLE TO USER tutempgmail01;

-- Cấp toàn bộ quyền trên database
GRANT ALL ON DATABASE TUKI_DB TO ROLE TUKI_ROLE;

-- Chuyển sang role DBT
USE ROLE TUKI_ROLE;

-- Tạo scheme
CREATE SCHEMA TUKI_DB.TUKI_SCHEMA;

CREATE SCHEMA TUKI_DB.TUKI_DEV_SCHEMA;

CREATE SCHEMA TUKI_DB.TUKI_PROD_SCHEMA;