-- Chuyển sang role ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Tạo data warehaouse
CREATE WAREHOUSE YOUTUBE_WH WITH WAREHOUSE_SIZE = 'X-SMALL';

-- Tạo database
CREATE DATABASE YOUTUBE_DB;

-- Tạo role cho DBT
CREATE ROLE YOUTUBE_ROLE;

-- Kiểm tra quyền trên warehouse
SHOW GRANTS ON WAREHOUSE YOUTUBE_WH TO ROLE YOUTUBE_ROLE;

-- Gán quyền sử dụng warehouse
GRANT USAGE ON WAREHOUSE YOUTUBE_WH TO ROLE YOUTUBE_ROLE;

-- Gán role cho user
GRANT ROLE YOUTUBE_ROLE TO USER tutempgmail101;

-- Cấp toàn bộ quyền trên database
GRANT ALL ON DATABASE YOUTUBE_DB TO ROLE YOUTUBE_ROLE;

-- Chuyển sang role DBT
USE ROLE YOUTUBE_ROLE;

-- Tạo scheme
CREATE SCHEMA YOUTUBE_DB.YOUTUBE_SCHEMA;

CREATE SCHEMA YOUTUBE_DB.YOUTUBE_DEV_SCHEMA;

CREATE SCHEMA YOUTUBE_DB.YOUTUBE_PROD_SCHEMA;